version: '3'
services:

  web:
    build:
      context: /home/alex/dev/Timofey/Bumble-Beezy-Squad/GeneratorApp/
      dockerfile: Dockerfile
    environment:
      OPENSSL_CONF: /usr/local/ssl/openssl.cnf
    volumes:
      - "/mnt/frontend/www:/var/www"
    ports:
      - "8080:80"
    depends_on:
      - nginx

  db:
    image: postgres:12
    environment:
      - ROOT_PASSWORD=1r2d21d
    volumes:
      - "/mnt/frontend/postgresql /var/lib/postgresql/ "
      - "/mnt/frontend/pos.cnf:/etc/pos.cnf"
    ports:
      - "3306:5432"

  nginx:
    image: nginx:stable
    volumes:
      - "/mnt/frontend/conf/nginx/etc/nginx:/etc/nginx"
      - "/mnt/frontend/log/nginx:/var/log/nginx"
    ports:
      - "80:80"
      - "443:443"